### ISSUE TITLE
Roles not installed from requirements.yml

### ISSUE THREAD

**Issue by jamesattard** [AdnanHodzic/containerized-wordpress-project#1]
Roles cannot be automatically installed, as per instructions (of course they work if installed manually from galaxy). I will assume that it is because this project is not using ansible-container. I suggest to update README.md accordingly.

```
(venv) ➜  containerized-wordpress-project git:(master) ✗ ansible-playbook containerized-wordpress.yml -i hosts
ERROR! the role 'AdnanHodzic.python-ubuntu-bootstrap' was not found in /home/james/code/containerized-wordpress-project/roles:/etc/ansible/roles:/home/james/code/containerized-wordpress-project

The error appears to have been in '/home/james/code/containerized-wordpress-project/containerized-wordpress.yml': line 74, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
  - AdnanHodzic.python-ubuntu-bootstrap
    ^ here
```

**Comment by AdnanHodzic** [comment]
Thanks for bringing this to my attention. 

I've just added meta/main.yml with list of all dependency roles. So once run this role will install all necessary roles automatically.

**Comment by AdnanHodzic** [comment]
Thanks for bringing this to my attention. 

Something changed in Ansible which prevented local setup/install of roles. In last couple of commits I made changes to code, and README has been updated.
