### ISSUE TITLE
docker-compose-setup is missing on Ansible Galaxy

### ISSUE THREAD

**Issue by prandelicious** [AdnanHodzic/containerized-wordpress-project#2]
The URL https://galaxy.ansible.com/AdnanHodzic/docker-compose-setup/ cannot be found on Ansible Galaxy

**Comment by AdnanHodzic** [comment]
Thanks for bringing this my attention, I renamed the role and forgot to update the link.

I've just updated the README file proper links, role you're looking for can be found on: https://galaxy.ansible.com/AdnanHodzic/docker-compose/
