### ISSUE TITLE
Support for SSL and HTTP2

### ISSUE THREAD

**Issue by prandelicious** [AdnanHodzic/containerized-wordpress-project#3]
Any plans of supporting SSL (LetsEncrypt) and HTTP2?

**Comment by AdnanHodzic** [comment]
Absolutely, this was next thing I wanted to do as part of this project, and it has been on my roadmap for some time now. 

Didn't have time to get it finished. I'll leave this issue open, so I can update and close it once this has been done, which I'm hoping will be soon.

**Comment by prandelicious** [comment]
Just a thought -- I read somewhere that **LetsEncrypt** will be supporting wildcard domains in 2018. Maybe you can use that as well 👍

**Comment by AdnanHodzic** [comment]
It'll definitely be LetsEncrypt. Wildcard support will make it a perfect solution, so I might wait that to be released first

**Comment by AdnanHodzic** [comment]
@prandelicious happy to report that support for HTTPS encryption using Let's Encrypt has been implemented in latest changes. 

Reference: https://foolcontrol.org/?p=2758
